# Builds, pushes, and deploys the Skyviewer API container
name: 'Build and deploy Skyviewer Client to Google App Engine in Dev'

on:
  push:
    branches:
      - 'master'

jobs:
  build-push-deploy:
    name: 'Build, Publish, and Deploy'
    runs-on: ubuntu-latest

    # Checkout the repository to the GitHub Actions runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # gcloud CLI setup
    - name: Login to GCP
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.SKYVIEWER_INT_SERVICE_ACCOUNT }}
        project_id: epo-integration-0e42
        export_default_credentials: true
    
    - name: Build Container Image
      run: |-
        docker build \
        -t "gcr.io/epo-integration-0e42/skyviewer-client:${{ github.sha }}" \
        --build-arg NEXT_PUBLIC_API_URL=https://skyviewer-api-e3g4rcii3q-uc.a.run.app/api \
        --build-arg NEXT_PUBLIC_ASSETS_BASE_URL=https://skyviewer-api-e3g4rcii3q-uc.a.run.app/assets \
        --build-arg NEXT_PUBLIC_ASTRO_API_URL=https://us-central1-skyviewer.cloudfunctions.net/astro-objects-api \
        .
    - name: Configure Docker Auth
      run: gcloud --quiet auth configure-docker

    - name: Push Container Image to GCR
      run: docker push gcr.io/epo-integration-0e42/skyviewer-client:${{ github.sha }}

    - name: Update app.yaml
      run: |-
        echo "
        network:
          name: epo-integration-vpc
          subnetwork_name: subnet-us-central1-01" >> app.yaml

    - name: Deploy to App Engine
      run: |-
        gcloud app deploy app.yaml \
        --image-url=gcr.io/epo-integration-0e42/skyviewer-client:${{ github.sha }} \
        --promote \
        --project=epo-integration-0e42